/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PromptRouteImport } from './routes/prompt'
import { Route as EvaluationRouteImport } from './routes/evaluation'
import { Route as EvaluateRouteImport } from './routes/evaluate'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SharedEvalIdRouteImport } from './routes/shared-eval.$id'

const PromptRoute = PromptRouteImport.update({
  id: '/prompt',
  path: '/prompt',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationRoute = EvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluateRoute = EvaluateRouteImport.update({
  id: '/evaluate',
  path: '/evaluate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedEvalIdRoute = SharedEvalIdRouteImport.update({
  id: '/shared-eval/$id',
  path: '/shared-eval/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/evaluate': typeof EvaluateRoute
  '/evaluation': typeof EvaluationRoute
  '/prompt': typeof PromptRoute
  '/shared-eval/$id': typeof SharedEvalIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/evaluate': typeof EvaluateRoute
  '/evaluation': typeof EvaluationRoute
  '/prompt': typeof PromptRoute
  '/shared-eval/$id': typeof SharedEvalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/evaluate': typeof EvaluateRoute
  '/evaluation': typeof EvaluationRoute
  '/prompt': typeof PromptRoute
  '/shared-eval/$id': typeof SharedEvalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/evaluate' | '/evaluation' | '/prompt' | '/shared-eval/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/evaluate' | '/evaluation' | '/prompt' | '/shared-eval/$id'
  id:
    | '__root__'
    | '/'
    | '/evaluate'
    | '/evaluation'
    | '/prompt'
    | '/shared-eval/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EvaluateRoute: typeof EvaluateRoute
  EvaluationRoute: typeof EvaluationRoute
  PromptRoute: typeof PromptRoute
  SharedEvalIdRoute: typeof SharedEvalIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/prompt': {
      id: '/prompt'
      path: '/prompt'
      fullPath: '/prompt'
      preLoaderRoute: typeof PromptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation': {
      id: '/evaluation'
      path: '/evaluation'
      fullPath: '/evaluation'
      preLoaderRoute: typeof EvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluate': {
      id: '/evaluate'
      path: '/evaluate'
      fullPath: '/evaluate'
      preLoaderRoute: typeof EvaluateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared-eval/$id': {
      id: '/shared-eval/$id'
      path: '/shared-eval/$id'
      fullPath: '/shared-eval/$id'
      preLoaderRoute: typeof SharedEvalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EvaluateRoute: EvaluateRoute,
  EvaluationRoute: EvaluationRoute,
  PromptRoute: PromptRoute,
  SharedEvalIdRoute: SharedEvalIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
